[package]
name = "p2p"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
iroh = "1.1.0"
reqwest = { version = "0.13.4", features = ["blocking"] }
aws-lc-rs = { version = "1.0.0-rc1" }
tokio = { version = "1.53.1", features = ["full"] }
rand = "0.9"

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_bytes = "0.11.19"
serde = "1.0.229"
rmp-serde = "1.3.1"

[lib]
name = "p2p"
path = "src/lib.rs"
